### ISSUE TITLE
Install only needed split subpackages

### ISSUE THREAD

**Issue by rmarquis** [Kwpolska/pkgbuilder#39]
PKGBUILDer is one of the rare helper that supports building of split packages. However, it currently always installs all built subpackages, instead of installing only the necessary subpackages.

The `makepkg --pkg` option was  very useful in this very situation but it has been removed in pacman/makepkg 5.0, so using `pacman -U` is the only alternative. This option _might_ however come back in the near future, see this [recent  discussion](https://lists.archlinux.org/pipermail/pacman-dev/2016-February/020856.html) on pacman-dev mailing list.

You can test this with the `python-novaclient` PKGBUILD, which builds the `python-novaclient` and `python2-novaclient` subpackages, and whose dependencies are also split packages.

**Comment by Kwpolska** [comment]
The problem is, this would become a special option hidden behind a switch, at best. The default behavior of `makepkg` is depended on by some people (including me with the `python-nikola-doc` package). And in most cases, having all the split packages installed is good enough (says the man who constantly runs out of `/` disk space).

The `python-novaclient` package works fine for me, and so does the aformentioned `python-nikola` family (installs `python2-nikola`, `python-nikola-doc`, and a ton of split makedepends). However, one of its dependencies (`python-oslo-utils`) lead to installing `community/` packages in the last (`pacman -U`) step, something I tried to prevent in my packages (via the large `makedepends` array; however, the AUR dependency builder picks AUR dependencies up correctly)

That said, if makepkg restores the option, I might support it. Otherwise, I would need to work out some hacks around the package detection part, which is already a hack.

(I’m not subscribed to the `pacman-dev` mailing list, please notify me if the option is restored.)

**Comment by AladW** [comment]
For comparison, see:
https://github.com/trizen/trizen/commit/3c94434c66ede793758f2bf7de84d68e3174e2ac
https://github.com/trizen/trizen/commit/0f8ddb11a732176f06658ebe062b7fc066f810e0

in particular, use of `makepkg --packagelist` to retrieve the package names.

**Comment by Kwpolska** [comment]
`makepkg --packagelist` isn’t necessary, since I could just look at the built .pkg.tar.xz files and compare it with .SRCINFO or whatever.

IMO it might not be worth the effort to support this; however, if anyone wants to implement it, I’ll happily take a pull request for this.
