### ISSUE TITLE
-Ss <regex> doesn't work the same between core and aur

### ISSUE THREAD

**Issue by FirefighterBlu3** [Kwpolska/pkgbuilder#41]
```log
$ pb -Ss "^grep$"
core/grep 2.23-1 (base base-devel) [installed]
    A string search utility
$ pb -Ss "^pkgbuilder$"
$ pb -Ss "pkgbuilder"
aur/pkgbuilder 4.2.4-2 (25 votes) [installed]
    A Python AUR helper/library.
aur/pkgbuilder-git 4.2.4.r1.gc797913-1 (2 votes)
    A Python AUR helper/library. (git version)
```

no form of regex works for AUR installed packages

**Comment by Kwpolska** [comment]
I'm afraid I can't fix this in any reasonable way. This option runs
pacman with that argument (and it supports regular expressions) and
then runs PKGBUILDer, which does not support any form of regex,
because the AUR search doesn't seem to support them either.

Please report an AUR bug if you want.
-- 
Chris Warrick <https://chriswarrick.com/>
PGP: 5EAAEA16
