### ISSUE TITLE
pb search iussue

### ISSUE THREAD

**Issue by GFdevelop** [Kwpolska/pkgbuilder#55]
Use `pb -Ss` not search aur packages if there are 2 or more words but only pacman repository packages, with one word it work (search in repo and aur).
try:
```
pb -Ss command not
pb -Ss command not found
```

I'm not using git version of pkgbuilder.

**Comment by Kwpolska** [comment]
There **is** a bug with handling spaces, which will be fixed in a while. But at the same time, note that [there are no results](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=%22command+not+found%22&outdated=&SB=n&SO=a&PP=50&do_Search=Go) for that search string in AUR. (Note the quotes, the API only allows exact searches like that.)

(You can try a search for `'hello world'` after this issue is fixed.)
